name: Checks

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: Compile arm64 and run nonprivileged checks
        run: make check
